language: node_js
sudo: false
node_js:
- '0.10'
- '0.12'
- '2.0.0'
- '4'
before_install:
  - npm install -g bower
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - bower install
  - npm install
after_script:
  - gulp coveralls
