FROM node:8

ADD . /bitcore

WORKDIR /bitcore

RUN npm install -D

# postinstall for lerna doesn't run properly so run explictly
RUN ./node_modules/.bin/lerna bootstrap

WORKDIR /bitcore/packages/bitcore-node

CMD npm run start