FROM amio/node-chrome
WORKDIR /bitcore

# Add source
COPY lerna.json ./
COPY package*.json ./

COPY  ./packages/bitcore-client/package.json ./packages/bitcore-client/package.json
COPY  ./packages/bitcore-build/package.json ./packages/bitcore-build/package.json
COPY  ./packages/bitcore-lib-cash/package.json ./packages/bitcore-lib-cash/package.json
COPY  ./packages/bitcore-lib/package.json ./packages/bitcore-lib/package.json
COPY  ./packages/bitcore-mnemonic/package.json ./packages/bitcore-mnemonic/package.json
COPY  ./packages/bitcore-node/package.json ./packages/bitcore-node/package.json
COPY  ./packages/bitcore-p2p-cash/package.json ./packages/bitcore-p2p-cash/package.json
COPY  ./packages/bitcore-p2p/package.json ./packages/bitcore-p2p/package.json
COPY  ./packages/bitcore-wallet-client/package.json ./packages/bitcore-wallet-client/package.json
COPY  ./packages/bitcore-wallet-service/package.json ./packages/bitcore-wallet-service/package.json
COPY  ./packages/bitcore-payment-protocol/package.json ./packages/bitcore-payment-protocol/package.json
COPY  ./packages/bitcore-wallet/package.json ./packages/bitcore-wallet/package.json
COPY  ./packages/insight-previous/package.json ./packages/insight-previous/package.json
COPY  ./packages/insight/package.json ./packages/insight/package.json

RUN npm install
RUN npm run bootstrap
ADD . .
RUN npm run compile
