#!/usr/bin/env node

var program = require('commander');
var Client = require('../lib/client');
var utils  = require('./cli-utils');
program = utils.configureCommander(program);

program
  .parse(process.argv);

var args = program.args;
utils.getClient(program, function (client) {
  client.createAddress(function(err, x) {
    utils.die(err);
    console.log('* New Address %s ', x.address);
  });
});
