ui: mocha-bdd
browsers:
  - name: chrome
    version: 30..latest
  - name: firefox
    version: 30..latest
  - name: ie
    version: latest
  - name: safari
    version: latest
browserify:
  - transform: brfs
