version: "3"

services:

  bitcore:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      DB_HOST: db
      DB_NAME: bitcore-test

  db:
    image: mongo

  bitcoin:
    build:
      context: test/docker/bitcoin
      args:
        VERSION: 0.15
