import { SCRIPT_TYPES } from './address';
import { ALGOS_BY_CHAIN, ALGO_TO_KEY_TYPE } from './algorithms';
import {
  CHAINS,
  EVM_CHAINS,
  EVM_CHAIN_ID_TO_CHAIN,
  EVM_CHAIN_NETWORK_TO_CHAIN_ID,
  MULTISIG_CHAINS,
  RIPPLE_CHAINS,
  SVM_CHAINS,
  UTXO_CHAINS,
} from './chains';
import { FEE_MINIMUMS } from './feeMinimums';
import { TOKEN_OPTS as opts } from './tokens';
import { UNITS } from './units';

export const Constants = {
  UTXO_CHAINS,
  EVM_CHAINS,
  SVM_CHAINS,
  RIPPLE_CHAINS,
  SCRIPT_TYPES,
  CHAINS,
  MULTISIG_CHAINS,
  ETH_TOKEN_OPTS: opts.ETH_TOKEN_OPTS,
  MATIC_TOKEN_OPTS: opts.MATIC_TOKEN_OPTS,
  ARB_TOKEN_OPTS: opts.ARB_TOKEN_OPTS,
  BASE_TOKEN_OPTS: opts.BASE_TOKEN_OPTS,
  OP_TOKEN_OPTS: opts.OP_TOKEN_OPTS,
  SOL_TOKEN_OPTS: opts.SOL_TOKEN_OPTS,
  UNITS,
  FEE_MINIMUMS,
  EVM_CHAIN_ID_TO_CHAIN,
  EVM_CHAIN_NETWORK_TO_CHAIN_ID,
  ALGOS_BY_CHAIN,
  ALGO_TO_KEY_TYPE
};