#!/usr/bin/env node

var program = require('commander');
var cli = require('../lib/clilib.js');
 
program
  .version('0.0.1')
  .command('create <walletName> <m-n> [username]', 'creates a wallet')
  .command('join <secret> [username]', 'join a wallet')
  .command('status', 'get wallet status')
  .command('send <address> <amount> <note>', 'send bitcoins')
  .parse(process.argv);



