#!/usr/bin/env node

var program = require('commander');
 
program
  .version('0.0.1')
  .command('create <walletName> <m-n> [username]', 'creates a wallet')
  .command('join <secret> [username]', 'join a wallet')
  .command('status', 'get wallet status')
  .command('address', 'create a new address from server')
  .command('addresses', 'list addresses')
  .command('balance', 'wallet balance')
  .command('send <address> <amount> <note>', 'send bitcoins')
  .parse(process.argv);



