#!/usr/bin/env node

var program = require('commander');
 
program
  .version('0.0.1')
  .command('create <walletName> <m-n> [username]', 'creates a wallet')
  .command('join <secret> [username]', 'join a wallet')
  .command('status', 'get wallet status')
  .command('address', 'create a new address from server')
  .command('addresses', 'list addresses')
  .command('balance', 'wallet balance')
  .command('send <address> <amount> <note>', 'send bitcoins')
  .command('sign <txpId>', 'sign a transaction proposal')
  .command('reject <txpId> [reason]', 'reject a transaction proposal')
  .command('broadcast <txpId>', 'broadcast a transaction proposal to the Bitcoin network')
  .command('rm <txpId>', 'remove a transaction proposal')
  .command('export', 'export wallet critical data')
  .parse(process.argv);



