#!/usr/bin/env node

var program = require('commander');
var cli = require('../lib/clilib.js');
var common = require('./common');

program
  .version('0.0.1')
  .option('-c,--config [file]', 'Wallet config filename')
  .parse(process.argv);

var args = program.args;

cli.setFilename(program.config);

cli.status(function(err, xx) {
  common.die(err);
  console.log(' * Status:', xx);
});

