#!/usr/bin/env node

var _ = require('lodash');
var program = require('commander');
var ClientLib = require('../lib/client');
var utils = require('./cli-utils');
program = utils.configureCommander(program);

program
  .usage('[options] walletname')
  .description('Creates a wallet on the remove server given the local information')
  .parse(process.argv);

var args = program.args;
if (!args[0])
  program.help();

var walletName = args[0];
var client = utils.getClient(program);
client.reCreateWallet(walletName, function(err) {
  utils.die(err);
  console.log(' *  Wallet Created.');
});
