#!/usr/bin/env node

var _ = require('lodash');
var program = require('commander');
var ClientLib = require('../lib/client');
var utils = require('./cli-utils');

program
  .version('0.0.1')
  .option('-c, --config [file]', 'Wallet config filename')
  .option('-h, --host [host]', 'Bitcore Wallet Service URL (eg: http://localhost:3001/copay/api')
  .option('-t, --testnet', 'Create a Testnet Wallet', String)
  .usage('[options] <walletName> <m-n> [copayerName]')
  .parse(process.argv);

var args = program.args;
if (!args[0])
  program.help();

var walletName = args[0];
var copayerName = args[2] || process.env.USER;
var network = program.testnet ? 'testnet' : 'livenet';

var mn = utils.parseMN(args[1]);

var client = utils.getClient(program);
client.createWallet(walletName, copayerName, mn[0], mn[1], network, function(err, secret) {
  utils.die(err);
  console.log(' * ' + _.capitalize(network) + ' Wallet Created.');
  if (secret)
    console.log('   - Secret to share:\n\t' + secret);
});
