#!/usr/bin/env node

var _ = require('lodash');
var program = require('commander');
var utils  = require('./cli-utils');
program = utils.configureCommander(program);

program
  .parse(process.argv);

var args = program.args;
utils.getClient(program, function (client) {
  client.getStatus(function(err, res) {
    utils.die(err);

    var x = res.wallet;
    console.log('* Wallet %s [%s]: %d-%d %s ', x.name, x.network, x.m, x.n, x.status);

    if (x.status != 'complete')
      console.log('  Missing copayers:', x.n - x.copayers.length);
    console.log('* Copayers:', _.pluck(x.copayers,'name').join(', '));

    var x = res.balance;
    console.log('* Balance %s (Locked: %s)', utils.renderAmount(x.totalAmount), utils.renderAmount(x.lockedAmount));

    utils.renderTxProposals(res.pendingTxps);
  });
});
