#!/usr/bin/env node

var _ = require('lodash');
var program = require('commander');
var utils = require('./cli-utils');
var Client = require('../lib/client');
program = utils.configureCommander(program);

program
  .parse(process.argv);

var args = program.args;
var client = utils.getClient(program);
client.getMainAddresses({
  doNotVerify: true
}, function(err, x) {
  utils.die(err);

  console.log('* Addresses:');
  _.each(x, function(a) {
    console.log('      ', a.address);
  });
});
