#!/usr/bin/env node

var _ = require('lodash');
var program = require('commander');
var utils  = require('./cli-utils');
var Client = require('../lib/client');

program
  .version('0.0.1')
  .option('-c, --config [file]', 'Wallet config filename')
  .option('-h, --host [host]', 'Bitcore Wallet Service URL (eg: http://localhost:3001/copay/api')
  .option('-v, --verbose', 'be verbose')
  .parse(process.argv);

var args = program.args;
var client = utils.getClient(program);
client.getAddresses(function(err, x) {
  utils.die(err);

  console.log('* Addresses:');
  _.each(x, function(a){
    console.log('      ', a.address);
  });
});
