#!/usr/bin/env node

var _ = require('lodash');
var program = require('commander');
var Client = require('../lib/client');
var utils  = require('./cli-utils');

program
  .version('0.0.1')
  .option('-c,--config [file]', 'Wallet config filename')
  .option('-v,--verbose', 'be verbose')
  .option('-h, --host [host]', 'Bitcore Wallet Service URL (eg: http://localhost:3001/copay/api')
  .usage('[options] <txpid> [reason]')
  .parse(process.argv);

var args = program.args;
var txpid = args[0] || '';
var reason = args[1] || '';
var client = utils.getClient(program);

client.getTxProposals({}, function(err, txps) {
  utils.die(err);

  var txp = utils.findOneTxProposal(txps, txpid);
  client.rejectTxProposal(txp, reason, function(err, tx) {
    utils.die(err);
    if (x.status == 'rejected')
      console.log('Transaction finally rejected.');
    else 
      console.log('Transaction rejected by you.');
  });
});
