#!/usr/bin/env node

var _ = require('lodash');
var program = require('commander');
var common = require('./common');
var Client = require('../lib/client');

program
  .version('0.0.1')
  .option('-c, --config [file]', 'Wallet config filename')
  .option('-v, --verbose', 'be verbose')
  .parse(process.argv);

var args = program.args;
var cli = new Client({
  filename: program.config
});

cli.getAddresses(function(err, x) {
  common.die(err);

  console.log('* Addresses:');
  _.each(x, function(a){
    console.log('      ', a.address);
  });

  if (program.verbose)
    console.log('* Raw Server Response:\n', x); //TODO
});
